# Generated by Django 4.1.2 on 2023-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='fechaCompra',
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='subtotal',
            field=models.BigIntegerField(default=0),
        ),
    ]
